<template> 
    <div>
        <Nav/>
    </div>
    <div>
        <Sidebar/>
        <BilaComp/>
        <BilaComp/>
        <BilaComp/>
        <BilaComp/>
        <BilaComp/>
        <BilaComp/>
    </div>
</template>